# Generated by Django 3.1.5 on 2022-02-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
