# Generated by Django 3.1.5 on 2022-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20220216_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default_user.png', null=True, upload_to='images/'),
        ),
    ]
